portiaAI/portia-sdk-python

.github/workflows/testing.yml

See https://michaelheap.com/access-secrets-from-forks/

Update github actions to use pull_request_target

---

portia/agents/context.py

This came up in the hackathon last week - when massive emails were included here, it made the prompts much more brittle

Reduce LLM broader context

---

.github/workflows/branch_checks.yml
.github/workflows/release.yml
pyproject.toml

What I'm hoping will happen here:
- It will automatically pick up the new tag, and publish this to pypi with the new release number

Make non-alpha release

---

portia/open_source_tools/__init__.py

Removes circular import in open_source_tools

---

portia/prefixed_uuid.py
pyproject.toml
tests/unit/test_portia.py

Renaming prefix to unblock backend.

Rename planrun prefix

---

tests/integration/test_e2e.py

Add a test with 2 consecutive action clarifications - this would have caught the issue yesterday.

Add clarification test

---

portia/execution_agents/execution_utils.py
portia/open_source_tools/search_tool.py
portia/tool.py
tests/unit/execution_agents/test_execution_utils.py

- Turn off summarisation for clarifications.
- Enable summarisation for the search tool.

[POR-877] Turnoff summarization for clarifications and enable in search tool

---

portia/tool_registry.py
tests/unit/test_tool_registry.py

Follow up PR will enhance the model generation slightly, to handle nested types a bit better (we see these in the dummy tools we've added)

Factor out utility method and add test for dynamic Pydantic model generation

---

.github/workflows/evals.yml
.github/workflows/release.yml
.github/workflows/testing.yml

Removing as discussed in https://github.com/portiaAI/portia-sdk-python/pull/144

Remove safe to test label

---

.github/workflows/evals.yml

This includes moving them to claude

Try to fix SDK evals again

---

portia/tool_registry.py

Some known issues are displaying every time as warning logs - these should be debug

Change pydantic model generation warnings to debug logs

---

pyproject.toml

Release 1.6.0 version

---

portia/portia.py
tests/unit/test_tool_registry.py

Enable org selection on deep links

---

portia/plan.py
pyproject.toml

- Make pydantic model change to allow for Step. I'll push this so I can allow adding new fields to be non-breaking changes.
- I'll also hotfix this in production, once the changes is ready to be pushed in Prod.

Make pydantic model change to allow for Step

---

portia/plan.py
tests/unit/test_plan_builder.py

Add support for conditionals in PlanBuilder.
Ticket Link: https://linear.app/portialabs/issue/POR-1055

Add conditionals support in builder

---

portia/portia.py

Persist resolve clarification result

Persist resolve_clarification result

---

portia/clarification.py

Removes generics from clarifications

remove generic clarification

---

example.py
portia/config.py
portia/portia.py
tests/integration/test_e2e.py
tests/unit/test_portia.py
tests/utils.py

Add introspection agent under feature flag

Add introspection agent under feature flag

---

.github/workflows/testing.yml

Env needed for https://github.com/portiaAI/portia-sdk-python/pull/248 tests 

Add GOOGLE_API_KEY to testing env

---

portia/config.py

Fix typo in Azure model names in LLMModel docstring

---

.github/workflows/evals.yml
pyproject.toml

Bump version to 0.1.9

---

.github/workflows/create-release-pr.yml

Action issues potential fix. Not using the right github action bot name matters I think. 

action update

---

.github/workflows/deploy_pypi.yml

Deploys on new tag creation, to be merged after testing PR tag creation works

deploy to pypi

---

portia/cloud.py
portia/config.py
portia/execution_agents/execution_utils.py
portia/execution_agents/utils/final_output_summarizer.py
portia/llm_wrapper.py
portia/logger.py
portia/mcp_session.py
portia/open_source_tools/image_understanding_tool.py
portia/open_source_tools/search_tool.py
portia/portia.py
portia/tool_registry.py
tests/integration/mcp_server.py
tests/integration/test_e2e.py
tests/integration/test_mcp_session.py
tests/unit/execution_agents/test_execution_utils.py
tests/unit/introspection_agents/test_default_introspection_agent.py
tests/unit/open_source_tools/test_search_tool.py
tests/unit/test_config.py
tests/unit/test_llm_wrapper.py
tests/unit/test_logging.py
tests/unit/test_plan.py
tests/unit/test_portia.py
tests/unit/test_tool_registry.py

No functional changes - I just ran `pre-commit run -a` so all the files are up-to-date

Run pre-commit over all files

---

.pre-commit-config.yaml

Add ability to run pyright using pre-commit

Add pyright pre commit

---

poetry.lock
pyproject.toml

Bump MCP SDK to latest version

---

portia/model.py

Adds the wrappers back that allow us to get tracing info in the planner evals

Add tracing to planner evals

---

.github/workflows/evals.yml
tests/integration/test_e2e.py

Comments on tests with why I think the changes are needed

Try to fix flakey tests

---

.github/workflows/create-release-pr.yml
.github/workflows/create-release-tag.yml

Fix Issue for PAT tag deployment

fix for PAT

---

poetry.lock
pyproject.toml

Updating our python versions to not require <4.0

Package python update

---

poetry.lock
pyproject.toml

Same as this one from main: https://github.com/portiaAI/portia-sdk-python/pull/301 

Python fix production

---

portia/_unstable/browser_tool.py

Allow for chromium args to be passed to the browser tool

---

README.md

Just changed the wording in the readme to encourage people to click the link.

Improve link to examples repo.

---

.github/workflows/evals.yml

Fix install for st

---

.github/workflows/evals.yml

fix for st

---

portia/model.py
tests/integration/test_model.py

Pass temperature through.
Model seed is not implemented in the Google SDK so cant currently be used.

Pass temperature through for GoogleGenAIGenerativeModel

---

.github/workflows/testing.yml
poetry.lock
portia/common.py
portia/config.py
portia/model.py
pyproject.toml
tests/integration/test_model.py

Ollama support

---

pyproject.toml

Minor version for changes around configuration

0.2 alpha version bump

---

portia/_unstable/browser_tool.py
portia/config.py
portia/open_source_tools/image_understanding_tool.py
portia/open_source_tools/llm_tool.py
tests/unit/open_source_tools/conftest.py
tests/unit/test_config.py

Meant to push this with the previous PR #313 but it didn't make it

Rename get_model to get_generative_model

---

.gitignore
portia/planning_agents/context.py
portia/storage.py
portia/templates/default_planning_agent.xml.jinja

Update to example plan prompting + update to defaults

example plans prompting

---

.github/workflows/create-release-tag.yml

Fix create-release-tag script

---

.github/workflows/evals.yml

Reflect https://github.com/portiaAI/platform/pull/333

Fix SDK evals for model name change

---

portia/portia.py
tests/unit/test_portia.py

[POR-1245] - Call save on plan_run

---

.github/workflows/evals.yml
portia/tool_registry.py
pyproject.toml
tests/unit/test_tool_registry.py

ASYNC MCP support

---

portia/open_source_tools/browser_tool.py

Post dogfood feedback around browser tool and browserbase

Update to use local rather than remote version of browser tool

---

portia/open_source_tools/browser_tool.py
tests/unit/open_source_tools/test_browser_tool.py

Auto captcha solving sometimes messes up, and its not necessary given we have HITL.

Disable auto captcha solving

---

portia/portia.py
tests/unit/test_portia.py

Handle empty user id

---

portia/portia.py

Add logging for version and models used on startup

---

portia/config.py
portia/portia.py

- Configure correct default models for introspection agent.
- Add some logging tweaks to make it clearer what happens for introspection evaluation. 

Introspection default model

---

portia/logger.py

Catch errors in the logging library.

Catch in logs

---

.github/workflows/create-release-tag.yml

Turns out, 'force' is ignored with create - you need to update.

Fix tagging

---

portia/open_source_tools/browser_tool.py
tests/unit/open_source_tools/test_browser_tool.py

Browser use tabs

---

portia/storage.py

Return the saved user

---

portia/tool.py
tests/integration/test_execution_agent.py
tests/unit/test_tool.py

Added a test with a tool with a large description as part of a new module for e2e tests for the execution agent

Allow 4096 char descriptions + add test

---

.github/workflows/create-release-tag.yml

In terms of testing, would it be ok to create a new release tag and then delete it?

Fix latest release tagging

---

portia/open_source_tools/browser_tool.py

Tune browser tool prompt to encourage agent not to get in a log-in loop.

Update prompt for browser tool

---

portia/portia.py
portia/tool.py
portia/tool_wrapper.py
tests/unit/test_portia.py
tests/unit/test_tool.py

Implemented a response class to model a ReadyResponse from a tool, that will soon return a list of clarifications.
Getting this in now with forwards compatibility so we dont get breaking changes against staging or prod.

Support future ready contract

---

portia/execution_agents/default_execution_agent.py

With this, GPT-4o templates better when it needs to.

Execution agent prompt engineering

---

example.py
portia/storage.py
tests/unit/test_storage.py

Merge on save

---

.cursor/context.md

Apparently this is a better place for this sort of context, and also allows people to have their own rules if they like.

Sort cursor files

---

portia/planning_agents/default_planning_agent.py
portia/portia.py
portia/templates/default_planning_agent.xml.jinja
tests/integration/test_e2e.py
tests/unit/test_portia.py

As discussed in knowledge share. Also includes a prompt update.

Update PlanInput to not require a LocalDataValue

---

portia/portia.py

llmtool via oneshot

---

portia/__init__.py
portia/portia.py
tests/unit/test_portia.py

Allow running a plan from ID rather than from the full plan

Allow running a plan by ID

---

portia/planning_agents/default_planning_agent.py
portia/templates/default_planning_agent.xml.jinja
portia/templates/example_plans.py

We had a couple of errors in the evals caused by producing bad tools (with a double colon - fixed by updating the prompt + example plans). I also updated the prompt to help Claude planners raise errors correctly.

Evals improvements

---

portia/open_source_tools/llm_tool.py

With this, we avoid the issue Sam saw 10/10 times in Langsmith.

LLM tool tweak

---

portia/portia.py
tests/unit/test_portia.py

This will make it obvious whether you're running against dev, staging or production

Add Portia API endpoint log line

---

portia/config.py
portia/execution_agents/one_shot_agent.py
tests/unit/execution_agents/test_oneshot_agent.py

Put one-shot agent clarifications behind feature flag

---

.pre-commit-config.yaml
portia/cli_clarification_handler.py

This allows running the hooks pre-push rather than pre-commit

Sort pre commit

---

.github/workflows/evals.yml
portia/execution_agents/default_execution_agent.py
portia/plan.py
portia/planning_agents/default_planning_agent.py
portia/templates/default_planning_agent.xml.jinja
tests/integration/test_e2e.py

The name changed on the backend but wasn't changed here, so we weren't receiving plan inputs from the backend. I've also updated the test so it would have caught this.

Plan input bug fix

---

portia/open_source_tools/browser_tool.py

I added this as part of the talk today and thought it would be helpful to merge

Add browser tool log line to easily get debug link

---

portia/end_user.py
portia/open_source_tools/browser_tool.py
tests/unit/test_end_user.py

Add remove additional data

---

portia/open_source_tools/browser_tool.py

Tighten language in browser tool prompt

---

portia/end_user.py
portia/open_source_tools/browser_tool.py
portia/plan.py

Fix plan pretty print

---

portia/open_source_tools/browser_tool.py
tests/unit/open_source_tools/test_browser_tool.py

Fix browser tool session management

---

.github/workflows/create-release-pr.yml
.github/workflows/create-release-tag.yml
.github/workflows/deploy_pypi.yml
uv.lock

Action fix

---

portia/storage.py

Remove plan input todo

---

portia/__init__.py
portia/portia.py
portia/storage.py
tests/unit/test_storage.py

* Prevent us getting error logs when we're just checking if a plan exists
* Expose Variable and PlanBuilder so they can be imported as 'from portia import Variable, PlanBuilder'

Small dogfooding improvements

---

portia/logger.py

Function location is not printed correctly in logging
before:
after:

Fix safelogger wrapper.

---

portia/open_source_tools/llm_tool.py
tests/unit/open_source_tools/test_llm_tool.py
tests/unit/test_portia.py

Structured LLM Tool: Useage as below
```python
from portia import Portia, config, PlanBuilder
from portia.open_source_tools.llm_tool import LLMTool
from portia.open_source_tools.weather import WeatherTool
import dotenv
from pydantic import BaseModel
dotenv.load_dotenv(override=True)
class StructuredOutput(BaseModel):
summary: str
config = config.Config.from_default()
structured_tool = LLMTool(
name="llm_tool_structured",
id="llm_tool_structured",
structured_output_schema=StructuredOutput,
)
weather_tool = WeatherTool()
tools = [structured_tool, weather_tool]
portia = Portia(config, tools=tools)
plan = (PlanBuilder("get the weather in london and summarize the weather")
.step("get the weather in london", tool_id=weather_tool.id)
.step("summarize the weather", tool_id=structured_tool.id) …
```

llm structured tool

---

portia/cli_clarification_handler.py
portia/planning_agents/default_planning_agent.py
portia/portia.py

Context: https://portiaai.slack.com/archives/C0825KS6F8Q/p1748360457645599

Planning prompt improvement

---

example.py

This wasn't actually raising a clarification on main and sometimes the calculator tool wasn't handling things correctly - now sorted.

Fix example

---

CONTRIBUTING.md

Fix README heading

---

portia/templates/default_planning_agent.xml.jinja

Fix planner retry

---

pyproject.toml
uv.lock

Add caching dependencies to 'all' install group

---

.github/workflows/evals.yml

Fix execution agent evals threshold file

---

portia/config.py

Match OpenAI - It seems odd to be using o3-mini for default model with azure

Fix azure openai default model (to gpt-4.1)

---

portia/clarification.py
portia/common.py
portia/execution_agents/clarification_tool.py
portia/execution_agents/output.py
portia/open_source_tools/browser_tool.py
portia/open_source_tools/calculator_tool.py
portia/open_source_tools/image_understanding_tool.py
portia/open_source_tools/llm_tool.py
portia/open_source_tools/local_file_reader_tool.py
portia/open_source_tools/local_file_writer_tool.py
portia/open_source_tools/pdf_reader_tool.py
portia/open_source_tools/search_tool.py
portia/open_source_tools/weather.py
portia/tool.py

This is a bigger change than I anticipated

Revert "Remove generics from tool def"

---

portia/plan.py
portia/planning_agents/default_planning_agent.py

Couple of improvements driven by the new E2E tests

Small Improvements from e2e

---

portia/execution_agents/context.py
portia/plan.py
portia/templates/default_planning_agent.xml.jinja
portia/tool_registry.py
pyproject.toml
tests/unit/execution_agents/test_context.py
tests/unit/planning_agents/test_default_planning_agent.py
uv.lock

Handle running MCP server better

---

pyproject.toml

Update pyproject.toml after cherry pick

---

portia/plan.py

improve description

---

portia/config.py
tests/unit/test_config.py
uv.lock

Support Google 2.5

---

.github/workflows/evals.yml

Match https://github.com/portiaAI/platform/pull/596

Remove tool ID check for evals

---

portia/tool_registry.py
tests/unit/test_tool_registry.py

Fix bug in omissible fields handling where multiple tools can impact one another

---

portia/telemetry/telemetry_service.py
pyproject.toml
tests/unit/open_source_tools/test_browser_tool.py
tests/unit/telemetry/test_telemetry_service.py
tests/unit/test_model.py
tests/unit/test_tool.py
uv.lock

Update instructor version

---

.github/workflows/daily-tests.yml
tests/integration/open_source_tools/test_browser_tool.py

Fix daily tests

---

portia/model.py
portia/open_source_tools/browser_tool.py
tests/unit/open_source_tools/test_browser_tool.py
uv.lock

fix for browser-use

---

portia/tool_registry.py

Fix SDK docs for tool descriptions

---

pyproject.toml
uv.lock

Tested this fix with new uv and poetry projects.

[POR-1686] Fixing python version errors by specifying python versions per dependency 

---

portia/open_source_tools/calculator_tool.py
portia/open_source_tools/llm_tool.py

Encourage use of calculator tool vs LLM tool

---

.github/workflows/trigger-downstream-updates.yml

Triggers updates on docs by calling repository dispatch action in docs repo

staging updater

---

portia/templates/default_planning_agent.xml.jinja
pyproject.toml
uv.lock

Updated langchain-google-genai as it included some fixes for structured_output and made a minor planning improvement based on evals.

Upgrade langchain-genai and minor planning prompt improvement

---

portia/execution_hooks.py

Fix fstring

---

portia/portia.py

Fix typing of example plans

---

README.md

Portia logo broken on pypi

---

portia/execution_agents/utils/step_summarizer.py
portia/tool.py
tests/unit/execution_agents/utils/test_step_summarizer.py

async step-summarizer

---

.cursor/rules/sdk-context.mdc
portia/introspection_agents/default_introspection_agent.py
portia/introspection_agents/introspection_agent.py
tests/unit/introspection_agents/test_default_introspection_agent.py

async impl for use in future async portia interfaces. 

async introspection

---

portia/model.py

Enable GPT-5

---

portia/tool.py
tests/unit/test_tool.py
tests/utils.py

The mcp client exception handling is.. painful.
Added detailed docstrings to explain the insanity.

Fix the timeouts from the mcp client

---

portia/builder/step_v2.py
portia/execution_agents/conditional_evaluation_agent.py
portia/portia.py
pyproject.toml

Adds a very simple "agent" for evaluating natural language conditions

Conditional evaluation agent - evaluate natural language conditions

---

portia/builder/step_v2.py

Add templating in string conditions

---

pyproject.toml
uv.lock

Fix SDK import error

---

example_builder.py
portia/builder/step_v2.py
portia/portia.py
tests/unit/builder/test_plan_v2.py
tests/unit/builder/test_step_v2.py
tests/unit/test_portia.py
uv.lock

PlanBuilderV2 - Nathan review follow-ups

---

data/earth-whispers/poem.txt
data/laser-sharks-ballad/poem.txt
example.py

The previous one wasn't throwing a clarification any more

Improve example

---

portia/builder/plan_v2.py
tests/unit/builder/test_plan_v2.py

Added pretty_print method in PlanV2
Ticket Link: #693 

feat(plan_v2): add pretty_print method for formatted plan output

---

README.md

Add Contributors section to README

---

.cursor/context.md
tests/unit/builder/test_plan_builder_v2.py
tests/unit/builder/test_plan_v2.py
tests/unit/builder/test_reference.py
tests/unit/builder/test_step_v2.py
tests/unit/telemetry/test_telemetry_service.py
tests/unit/test_common.py

I did this with cursor, but have checked the tests looked ok (and Claude promised me he didn't change any tests lol: "I can confirm that I only changed the structural organization - zero test logic was modified")

Move away from class tests

---

portia/builder/reference.py
portia/builder/step_v2.py
portia/execution_agents/react_agent.py

override fix
