portiaAI/portia-sdk-python

CONTRIBUTING.md
portia/errors.py
tests/unit/open_source_tools/test_search_tool.py
tests/unit/test_plan.py

* Added a line about linting to the contributing docs
* Ran the linter over all files in the repo which gave a couple of changes
I tried setting up pyright through pre-commit too (using https://github.com/RobertCraigie/pyright-python) but unfortunately it doesn't really work because it can't (easily) pick up the python virtual environment set up by poetry.

Add linting to contributing docs

---

portia/agents/verifier_agent.py
tests/unit/agents/test_verifier_agent.py

This toggles the `made_up` flag to trigger a clarification for None values depending on whether it's required or not. 
A local LangSmith run shows that this:
- Increases tool called by 5%
- Increases correct tool args by 3%
- Increases only_necessary_clarifications_requested by 4%
Against the most recent run

Adds constraints on None values generated by the argument parser.

---

portia/agents/execution_utils.py
tests/unit/agents/test_execution_utils.py

Step summary is only populated for tools that has summary flag turned on. We should always have something in the summary (user feedback), because so it can be always used if needed rather than checking if it's None.
- Serialise the output value into the summary if not provided.

[POR-691] Summary should be populated with values if it is None

---

portia/runner.py
pyproject.toml
tests/unit/test_runner.py

`wait_for_ready` isn't resolving actions clarifications when the tool is ready. Which leads to hanging auth clarifications. (**non-cloud storage**).
Updating tests and resolve all action clars. when the tool is ready.

[RUN-26] Fix wait_for_ready to resolve all action clarifications when ready_to_resume

---

portia/cli.py
portia/llm_wrapper.py
portia/open_source_tools/search_tool.py
portia/templates/example_plans.py
portia/templates/query_planner.xml.jinja
tests/unit/planners/test_one_shot_planner.py

* Explicitly mention Tavily in the search tool so the LLM can link it up with evals that say 'search Tavily to xxx'
* Use real tools in the example plans to make them more realistic
* Changes to improve the planner prompt. The most important one here was removing the second 'tools' usage - this was massive and made the prompt huge which then reduced accuracy. I found even with just removing this, example plans started to work.
* Add a wrapper around OpenAI client in the planner so we can get traces to Langsmith. Unfortuantely they don't have equivalents for Anthropic / Mistral, but I still found this v v useful for testing so thought it was worth committing.

Eval quality improvements

---

portia/runner.py
pyproject.toml
tests/unit/test_runner.py

`wait_for_ready` was not resolving the clarifications correctly, since we pull workflow object every-time in the loop. This has resulted in `current_step_clarifications` to have references to old workflow object. This bug has surfaced once we merged the change to remove cloud resolving clarifications in prod.
Pull once the workflow, and no need to re-pull since SDK is the one responsible for writing states now.

Fix wait_for_ready to pull workflow once

---

pyproject.toml

Evals run locally good: https://smith.langchain.com/o/e2eb5117-7ff4-446a-b9ac-b768f33886e1/datasets/0992e8df-137f-4881-b019-59399acb5e80?paginationState=%7B%22pageIndex%22%3A0%2C%22pageSize%22%3A10%7D 
I'll follow up to update evals as well to use this latest.

bump version to make evals use new verifier prompt

---

portia/cli.py
portia/errors.py
portia/portia.py

* Suppress stack trace from config.py when there is invalid config
* Add a method to set and save the plan run state in portia.py - I saw this pattern quite a lot and thought it would be safer to have it behind a method so we always make sure to save to the cloud when updating the state

Logging change + portia.py small tidy

---

portia/config.py
portia/logger.py
portia/portia.py
tests/unit/test_config.py
tests/unit/test_logging.py

- color the function name in the log according to 
- plan announcements -> code 39
- plan run and step announcements -> code 129
- tool call and clarification announcements -> 87
- include the link to the dashboard in the plan execution

More log improvements

---

portia/portia.py

Output a warning message on startup if no API key is present indicating that Portia Cloud tools are not available

Warn if no Portia API key is present

---

.github/workflows/release.yml

This means SDK rollouts need to be triggered manually, rather than automatically from a PR. Once this is merged, I'll make the other changes in https://portiaai.slack.com/archives/C07UK7NB49L/p1741346336545249.

Prevent automatic SDK rollouts

---

portia/logger.py
tests/unit/test_logging.py

we will see error like 
```
ValueError: Tag "<repository_name>" does not correspond to any known color directive, make sure you did not misspelled it (or prepend '\' to escape it)
```
if the log message has `<>` in it
Tested with query `star all of the repos belonging to <PortiaAI>`

Fix formatting issue when log message has '<>'

---

poetry.lock
portia/__init__.py
portia/mcp_session.py
portia/tool.py
portia/tool_registry.py
pyproject.toml
tests/integration/mcp_server.py
tests/integration/test_mcp_session.py
tests/unit/test_tool.py
tests/unit/test_tool_registry.py
tests/utils.py

This PR adds a wrapper around the [MCP python SDK](https://github.com/modelcontextprotocol/python-sdk), enabling users to create a (portia) `ToolRegistry` for their application that calls out to an MCP server.
Example usage:
```python
tools = DefaultToolRegistry(config) + McpToolRegistry.from_stdio_connection(
server_name="fetch",
command="uvx",
args=["mcp-server-fetch"],
)
portia = Portia(config=config, tools=tools)
plan = portia.run(
"Fetch the current stories from BBC News, summarize them and then add them to the file 'bbc_news.txt'"
)
```
To do before merging

Add MCP tool integration

---

portia/cloud.py
portia/storage.py
portia/tool.py
portia/tool_registry.py
tests/integration/test_portia_cloud.py
tests/unit/test_storage.py
tests/unit/test_tool.py

By using a single HTTPX client for all cloud operations we can limit on the SDK side concurrent requests. This fixes the concurrency issues we are having.

[POR-960] Move to a global client to limit in-flight requests

---

.github/workflows/testing.yml
portia/tool_registry.py

During cost exploration, I found that part of the issue was a [workflow from the MCP branch](https://github.com/portiaAI/portia-sdk-python/actions/runs/13794105351) that took 6 hours 😬 !
The tests will normally take under 5 minutes if there is nothing wrong

Limit testing workflow time to 10 minutes

---

poetry.lock
pyproject.toml

Fixes issue caused by latest instructor release (today):
```
File "/Users/samstephens/Library/Caches/pypoetry/virtualenvs/docs-test-k--WC6Rb-py3.13/lib/python3.13/site-packages/instructor/__init__.py", line 110, in <module>
if importlib.util.find_spec("google.genai") is not None:
~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
File "<frozen importlib.util>", line 91, in find_spec
ModuleNotFoundError: No module named 'google'
```

Limit instructor version to be less than 1.7.6 (latest) due to broken import check

---

poetry.lock
pyproject.toml

🤦 
It appears I was over-optimistic about rolling back - 1.7.5 is broken too, it appears 1.7.6 issue was an attempted bug fix
Author of release is fixing this now https://github.com/instructor-ai/instructor/issues/1416

Limit instructor version to be less than 1.7.5 (latest-but-one) due to broken import check

---

portia/execution_agents/utils/final_output_summarizer.py
portia/portia.py
tests/unit/execution_agents/utils/test_final_output_summarizer.py
tests/unit/test_portia.py

- This is fix to final output for conditional cases for resuming cases (or after resolving clarifications), where currently we initialise the `last_executed_step_output` with None. Instead, we should properly, retrieve it back from the PlanRun object.
-  Add the summary instead of value for final step summarizer, so it can provide more comprehensive summary of what has decisions that had been done in the plan run. 

Fixing final output with conditionals

---

CONTRIBUTING.md
README.md
poetry.lock
portia/common.py
portia/config.py
portia/execution_context.py
portia/llm_wrapper.py
pyproject.toml
tests/unit/planning_agents/test_default_planning_agent.py
tests/unit/test_config.py
tests/unit/test_llm_wrapper.py
tests/unit/test_portia.py

OpenAI and Anthropic are left as "default" for now - thoughts?
Added a guard for imports to direct people to install if they try to use Mistral without the extra dep
Usage: 
`poetry install portia-sdk-python[mistral]`
For local development:
`poetry install --all-extras`

Move mistral to optional / extras dependency

---

portia/cloud.py
portia/config.py
portia/portia.py
portia/tool_registry.py
tests/integration/test_e2e.py

Based on user feedback
If you haven't got an API key set then the planner can fail when building more than a trivial plan because the tools available are limited.
This PR introduces a log message that only gets triggered if:
- the user has no API key
- the Plan generation fails
- the replan with Portia cloud tools does not fail
[Ticket Link](https://linear.app/portialabs/issue/POR-829)
```python
from portia import Portia, Config
portia = Portia(config=Config(portia_api_endpoint="https://api.porita.dev"))
portia.run("Send an email to example@example.com about farm yard animals")
```
Results in 

Plan with cloud tools on error

---

.github/workflows/create-release-pr.yml
.github/workflows/create-release-tag.yml

Adds in tag actions for release creation that automatically open PR and bump pyrpoject version and create tag on merge close of branches of form 'release/v'
To follow after testing:
Deploy action for on tag creation
- on new tag of form v\d.\d.\d[-alpha] publish to pypi. This allows for manual tag creation in the event of requiring override.

tag action v1

---

portia/execution_agents/default_execution_agent.py
portia/execution_agents/one_shot_agent.py
portia/execution_agents/utils/step_summarizer.py
pyproject.toml
tests/unit/execution_agents/utils/test_step_summarizer.py

- This is to fix the step summary to be more accurate the nature of the output of the tools. E.g. for google tools check availability tool is mistakenly assumes the output is an event created.
- The fix is to include the tool's description (and output schema..etc), when summarising the output. This also helps the introspection takes more accurate decisions based on output of steps.
Ticket Link: https://linear.app/portialabs/issue/POR-1089/summarizer-producing-bad-output-for-google-calendar-tool
**Before**:
```
"value": "[{\"start\": \"2025-04-01T00:00:00+0000\", \"end\": \"2025-04-03T00:00:00+0000\"}]",
"summary": "Event scheduled from April 1 to April 3, 2025."
```
**After**:
```
"value": "[{\"start\": \"2025-04-01T00:00:00+0000\", \"end\": …
```

Fixed the step summarizer to include tool's description in context

---

portia/cli.py

CLI double plans atm, leading to issues with the stated plan and input/output/tool matching. 

fix for double planning

---

portia/llm_wrapper.py
tests/unit/test_llm_wrapper.py

In order to make the change in this release smaller and not user-code breaking, bring back the LLMWrapper as a thin wrapper around `GenerativeModels`, with a `DeprecatedWarning`

Bring back LLMWrapper as deprecated and decoupled from everything

---

poetry.lock
portia/_unstable/browser_tool.py
pyproject.toml

Add browserbase support to the browser tool and create the concept of BrowserInfrastructure which enables Browserbase, Local chrome or others to be swapped in and out.
**Coming up next**
- Integration with tool registries
- SDK documentation improvements
- Tests and moving out of unstable
Ticket Link: https://linear.app/portialabs/issue/POR-1019/create-browserbase-version-of-tool
- [ X] New feature 
- [ X] Refactor

[POR-1019] Add browserbase support to browser tool

---

portia/_unstable/browser_tool.py
portia/config.py
portia/open_source_tools/image_understanding_tool.py
portia/open_source_tools/llm_tool.py
portia/open_source_tools/registry.py
portia/portia.py
portia/tool.py
portia/tool_registry.py
tests/integration/test_e2e.py
tests/integration/test_portia_cloud.py
tests/integration/test_runner_context.py
tests/unit/test_portia.py
tests/unit/test_tool_registry.py

Step 1 of simplifying config: Allow user to provide `GenerativeModel` to `LLMTool`, `ImageUnderstandingTool` and `BrowserTool`
Simplified ToolRegistry based on observation that the only real difference between different implementations is the instantiation, the rest is the same.
Ticket Link: [POR-1143](https://linear.app/portialabs/issue/POR-1143/simplify-config)

Refactor ToolRegistry to simplify code. Add model field to LLMTool, Image tool and browser tool

---

portia/execution_agents/context.py
portia/execution_agents/default_execution_agent.py
portia/execution_context.py
portia/open_source_tools/image_understanding_tool.py
portia/open_source_tools/llm_tool.py
portia/planning_agents/base_planning_agent.py
portia/planning_agents/context.py
portia/planning_agents/default_planning_agent.py
portia/portia.py
tests/unit/execution_agents/test_base_execution_agent.py
tests/unit/execution_agents/test_context.py
tests/unit/open_source_tools/test_image_understanding_tool.py
tests/unit/planning_agents/test_default_planning_agent.py

Removes the ability to add system context extensions via execution context. This is the first step in removing execution context. 
Associated docs change: https://github.com/portiaAI/docs/pull/83/files

[POR-1094] - Remove system context extensions

---

poetry.lock
pyproject.toml

rsa is brought by google optional dependency, so fixed by adding some constraints on `google-generativeai`  to force removing the rsa 4.2 which has [this vulnerability](https://github.com/portiaAI/portia-sdk-python/security/dependabot/3).
By constraining the python version, it forced poetry to use the same version of dependency across the dependency graph for this package, which is why it pulled in the latest package for rsa.
```
└── google-generativeai (optional dependency)
└── google-api-core
└── google-auth
└── rsa
``` 

Rsa vulnerability fix

---

portia/planning_agents/default_planning_agent.py
portia/templates/default_planning_agent.xml.jinja
tests/integration/test_e2e.py

``` Test: test_portia_run_query_requiring_cloud_tools_not_authenticated ``` is failing 1 in 5, duo to producing plans with 0 steps.
- Fix: Made some planning prompt edits to highlight it should return error instead.
``` Test: test_portia_run_query_with_example_registry ``` is failing 1 in 7, duo haiku step is selecting search_tool instead of llm_tool. 
- Fix: Made some minor edit in the query to nudge it towards LLM tool.
Both now are passing 10 times in a row, so should be more stable.

Fix two flaky tests

---

portia/cli.py
portia/config.py

Without this, I get the below error with cli.py
```
poetry run python -m portia.cli run "Get the weather in London, then write a poem about Robbie Heywood in London experiencing the current weather, then email it to robbie@portialabs.ai" --env-location ENV_FILE --default-log-level debug
2025-04-14 20:01:30.387 | ERROR | __main__:_get_config:352 - Config value NONE is not valid - Value must be a string or LLMProvider
```

Fix cli.py

---

portia/cli.py
portia/config.py

Re-enables `--llm-provider` 
Enables e.g. `--default-model=anthropic/claude-3-5-sonnet-latest` or `--planning-model=openai/gpt-4o`
Handle `Enum | None` fields (in an admittedly brittle way) and fields from the `GenerativeModelsConfig`

Improve CLI config for models and providers

---

portia/cli.py
pyproject.toml
tests/unit/test_cli.py

Mocks out Portia class and tests the CLI interface is working as expected
Mainly just checks the Config type. Because we have good validations on this, it feels like sufficient testing for now (certainly better than nothing)
Ticket Link: https://linear.app/portialabs/issue/POR-1266/add-tests-for-portia-cli

Add some basic CLI unittests

---

portia/clarification_handler.py
portia/cli.py
portia/cli_clarification_handler.py
tests/unit/test_cli_clarification_handler.py

This PR moves the CLIClarificationHandler from cli.py to a new file cli_clarification_handler.py to improve code organization and maintainability.

Move CLI clarification handler to a separate file

---

portia/open_source_tools/llm_tool.py
tests/unit/open_source_tools/test_llm_tool.py

The Execution Agent sometimes fails to pass inputs to the LLM Tool - it seems to think that the `task` argument should be the same as the Step task parameter, but that then misses inputs (variables and other context).
See doc for context of the decisions that went into fixing this: https://docs.google.com/document/d/1p3I8M9YnL5w2o1JMmFevbGrCHqWH0b0PiLY_bpSuTJE/edit?tab=t.0

Add extra argument to LLMTool `input_data: list[str]`

---

portia/clarification.py
portia/cli_clarification_handler.py
portia/open_source_tools/browser_tool.py
tests/unit/open_source_tools/test_browser_tool.py
tests/unit/test_cli_clarification_handler.py

Add variant of action clarification that requires user confirmation. Used within browser tools so that the user can perform authentication and then indicate that they have done so.
Ticket Link: https://linear.app/portialabs/issue/POR-1242/create-a-cli-handler-that-works-for-browser-based-tools
- V0.2.2 Added a variant of ActionClarification which expects confirmation from the user once the action has been completed.

[POR-1242] Add variant of action clarification that requires user confirmation

---

.github/workflows/evals.yml
portia/templates/default_planning_agent.xml.jinja
tests/integration/test_e2e.py

- Add one e2e test to verify outputs are following into inputs as expected.
- Fix GH summary for introspection agent evals ([successful summary](https://github.com/portiaAI/portia-sdk-python/actions/runs/14623002112)).
Ticket Link: https://linear.app/portialabs/issue/POR-1252/add-e2e-test-to-capture-outputs-passed-as-inputs-in-steps

Added e2e test for input/ouputs dependencies

---

portia/model.py
tests/integration/test_e2e.py
tests/unit/test_model.py

Claude 3.5 defaults to 1024 tokens output which breaks the execution agent for larger (tool) inputs. This is a problem for the LLM tool, which sometimes need passing the large values via the new `input_data: list[str]` arg.
Claude 3.5 and 3.7 also struggle with structuring the JSON for large inputs into tool arguments (see eval PR link below). 
Instructor JSON mode doesnt have this problem, but it does introduce overhead of extra input tokens and introduces a separate problem where Claude writes a message before the JSON (because we are using Instructor `Mode.ANTHROPIC_JSON`)
For this reason, I've implemented the instructor mode as a fall back ONLY when Claude is trying to parse a large value into a JSON (which you can determine by asking Langchain to return raw responses)
Related eval PR …

Anthropic models: Increase max tokens and fall back on instructor for structured output

---

portia/portia.py

Ticket Link: [POR-1211](https://linear.app/portialabs/issue/POR-1211/we-should-show-the-plan-in-the-logs-output-without-the-toolids)

Do not show toolIDs in log output for plan

---

portia/portia.py
portia/tool.py
portia/tool_registry.py
tests/unit/test_tool_registry.py

Handles serialization of non-nullable omissible fields: fields that are not required in the JSON schema, but that are not nullable. Pydantic has no concept of an omitted field, so we must for it to be nullable and then make sure we don't serialize any None values.
See ticket desc for more info
Tested this with the Stripe example that was causing issues and no clarifications were raised, tools called correctly.
Ticket Link: https://linear.app/portialabs/issue/POR-1260/fix-for-optional-but-non-nullable-arguments-from-json-schema-incl-mcp 

Handle JSONSchema omissible fields in pydantic model generation

---

portia/storage.py

Send an empty string rather than None if there is no summary. This should almost never be hit, but can be hit in weird circumstances (e.g. when I moved the memory threshold very low for testing).

Small memory update

---

portia/portia.py
tests/integration/test_e2e.py

When debugging a flakey test `test_portia_run_query_requiring_cloud_tools_not_authenticated` I realised we dont exit with a PlanError if the _replan_ fails. This change makes sure we always to exit with a PlanError in this case.
Also improved the flakey test by adding email address to the prompt (the reason for the flake was that the planner complained about lack of email address sometimes (actually very rarely, which is odd)

Make sure if portia-cloud-replan fails we still exit with PlanError

---

portia/execution_agents/base_execution_agent.py
portia/execution_agents/default_execution_agent.py
portia/execution_agents/memory_extraction.py
portia/execution_agents/one_shot_agent.py
portia/portia.py
tests/unit/execution_agents/test_base_execution_agent.py
tests/unit/execution_agents/test_default_execution_agent.py
tests/unit/execution_agents/test_memory_extraction.py
tests/unit/execution_agents/test_oneshot_agent.py

Adds agent memory to one-shot agent. I originally wasn't sure about doing this, but realise we def should now tunic are using it. Most of the diff is just moving the MemoryExtractionStep into its own file.

Add agent memory to one-shot agent

---

portia/introspection_agents/default_introspection_agent.py

Simplify one of the conditions and assert when to use it for complete condition. This is to fix a false positive that happens sometimes where it prefers COMPLETE rather than SKIP.

Added minor edit to prompt to force not using this complete condition for skip cases

---

portia/config.py

I think this is ready to be turned on by default. If everything goes well for a week, I'll remove the feature flag and commit to this.

Turn on agent memory feature flag by default

---

poetry.lock
pyproject.toml

Browser use version 0.1.41 updates some params in a non-backwards compatible way. We're also pinned anyway at the moment because 0.1.41 depends on a later version of Ollama, so for now, I'd rather just be explicit on the pinning.

[RUN-48] Pin browser-use version

---

portia/portia.py

Without this, even when we resolve a clarification async, we don't re-fetch the plan_run and so we don't pick up that change.

Sort async clarification handling

---

example.py
portia/introspection_agents/default_introspection_agent.py
portia/plan.py
portia/planning_agents/default_planning_agent.py
portia/portia.py
portia/storage.py
portia/templates/default_planning_agent.xml.jinja
tests/integration/test_e2e.py
tests/unit/planning_agents/test_default_planning_agent.py
tests/unit/test_plan.py
tests/unit/test_portia.py
tests/unit/test_storage.py

Changes after our plan inputs dogfooding session:
* Allow calling public methods with dicts
* Change PlanInput to have an optional value and use lists of them
* A few spelling tweaks in prompts
* Change plan field from `inputs` to `plan_inputs`
* Add an indent to plan pretty printing

Updates from plan input dogfooding

---

portia/open_source_tools/llm_tool.py
tests/unit/open_source_tools/test_llm_tool.py

The current input for the `llm_tool` is forcing gemini model (2.0 flash) to try to parse the big input (search results) into list of str in tool agent node, which is causing `MALFORMED_FUNCTION_CALL` ([example](https://smith.langchain.com/o/e2eb5117-7ff4-446a-b9ac-b768f33886e1/projects/p/500223c8-b833-4853-9ef6-0016c236461a?timeModel=%7B%22duration%22%3A%227d%22%7D&peek=236f0c1b-0a8f-4471-851a-25fb629ba829&peeked_trace=ff9fa307-5d94-475e-a15a-01ee89d90c59)) for a lot of cases because of tavily search results. We need to fix this for 2.0 flash because they can't upgrade to gemini 2.5 atm.
I relaxed the input types for `llm_tool` to accept it as `List[Any] | str | None` instead of `List[str]` only, then handle casting it back internally to list of str in the tool itself. 
This has forced …

[RUN-44] Update llm_tool to handle variaty of inputs to make use of memory agent

---

portia/portia.py

Without this, we call before `before_first_step_execution` when resuming a plan after handling a clarification, which I don't think is the right behaviour

Add step check to before_first_step_execution

---

portia/logger.py
portia/tool_wrapper.py
tests/unit/test_logging.py

Without this, I was seeing loguru errors with e.g.
```
Traceback (most recent call last):
File "/Users/robbieheywood/Library/Caches/pypoetry/virtualenvs/portia-sdk-python-Dp6bM8CF-py3.13/lib/python3.13/site-packages/loguru/_handler.py", line 164, in emit
_, precomputed_format = self._memoize_dynamic_format(dynamic_format, ansi_level)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/robbieheywood/Library/Caches/pypoetry/virtualenvs/portia-sdk-python-Dp6bM8CF-py3.13/lib/python3.13/site-packages/loguru/_handler.py", line 14, in prepare_colored_format
colored = Colorizer.prepare_format(format_)
File "/Users/robbieheywood/Library/Caches/pypoetry/virtualenvs/portia-sdk-python-Dp6bM8CF-py3.13/lib/python3.13/site-packages/loguru/_colorizer.py", line 367, in prepare_format …
```

Prevent logging errors

---

portia/planning_agents/default_planning_agent.py
portia/templates/default_planning_agent.xml.jinja

In the evals (example: https://smith.langchain.com/o/e2eb5117-7ff4-446a-b9ac-b768f33886e1/datasets/819a5146-d5e9-42a0-a585-f95d02e37460/compare?selectedSessions=664a6204-950f-47ed-b1d0-3e4c15ce482b&baseline=undefined&sort_by=is_plan_generated&sort_order=ASC), we're seeing a few responses like:
`{"steps":[],"error":"Missing required end user email. The query requires scheduling a calendar event which needs the user's email address to check availability and create the event, but no email address was provided in the EndUser section."}`
This is because we don't set this info for the end user the evals are running with. I think this should fix that.
(If applicable, add a changelog …

Only show end-user info to planning agent if it exists

---

.github/workflows/evals.yml

We should run evals on the SDK after merge with `run=main` so that we can filter on `run=main` and just see how the evals on main change over time (as we can with the platform repo).
Also changes the langchain project from a secret to a variable so links render properly.

Run SDK evals on merge

---

tests/utils.py
uv.lock

Fixes bug in tests for python 3.11 
```
Traceback:
tests/unit/test_tool.py:23: in <module>
from tests.utils import (
tests/utils.py:6: in <module>
from typing import TYPE_CHECKING, Any, override
E   ImportError: cannot import name 'override' from 'typing' (/Users/samstephens/.local/share/uv/python/cpython-3.11.11-macos-aarch64-none/lib/python3.11/typing.py)
```

Use backport typing @override for python < 3.12

---

portia/execution_agents/default_execution_agent.py
portia/planning_agents/default_planning_agent.py
portia/templates/default_planning_agent.xml.jinja
tests/unit/execution_agents/test_default_execution_agent.py

Interestingly, adding explanation before it chooses the made_up field essentially works as a chain of thought, which helps it get the right answer. Adding the tool description also helps.
I've also included a couple of end user fixes - these are what is needed to get https://github.com/portiaAI/platform/pull/462 in (occasionally things break because the agent thinks there is an issue when it is passed an empty end user bock).

Sort execution agent email fussiness

---

portia/config.py
portia/model.py
tests/integration/test_e2e.py
tests/integration/test_model.py
tests/unit/test_cli.py
tests/unit/test_config.py
tests/unit/test_portia.py

The CLI was broken for Azure OpenAI and Google:
- For azure, because the name has a hyphen in it instead of an underscore, which `parse_str_to_enum` couldn't handle
- For Google, because the enum value and name are different, even accounting for case and hyphen vs underscore
The fact that the Google provider is called `GOOGLE_GENERATIVE_AI` in some places and `google` in others is confusing, so I've standardised around `google` - this change is backwards compatible (alias in enum)

Fix CLI for azure and google providers, rename enum `GOOGLE_GENERATIVE_AI` to `GOOGLE`

---

portia/config.py
portia/portia.py
tests/unit/test_config.py

Allow using `.portia` as the default storage directory

Allow a default storage dir

---

.github/workflows/evals.yml
portia/common.py
portia/config.py
portia/model.py
pyproject.toml
tests/integration/test_e2e.py
tests/unit/test_config.py
tests/unit/test_model.py
tests/utils.py
uv.lock

- Add `llm_cache_redis_url` config option and propagate to model builders
- Setup LangChain RedisCache when creating LLM models
- Implement manual caching in instructor methods
- Test new configuration and caching behaviour

Add Redis caching for LLM calls

---

portia/cli_clarification_handler.py
portia/execution_agents/default_execution_agent.py
portia/planning_agents/default_planning_agent.py
portia/templates/default_planning_agent.xml.jinja
pyproject.toml
tests/unit/execution_agents/test_default_execution_agent.py
tests/utils.py
uv.lock

See commits cherry-picked for release
release-hotfix-v0.3.9 state is the v0.3.8 tag (current latest SDK release)
Plan is to tag from the release-hotfix-v0.3.9 branch once this PR is merged
I've included the backport for the typing fix as that causes failures for 3.11 which is officially supported, and my local pre-commit hooks were broken without it

Release 0.3.9 PR - Planning prompt fix for anthropic

---

portia/portia.py
tests/unit/test_portia.py

As discussed on slack, this stops us running before_step_execution after a clarification

Don't run before_step_execution after a clarification

---

portia/mcp_session.py
portia/tool_registry.py
pyproject.toml
tests/integration/mcp_server.py
tests/integration/test_mcp_session.py
tests/unit/test_tool_registry.py
uv.lock

Updates MCP SDK and adds support for streamable MCP
https://linear.app/portialabs/issue/POR-1480/support-streamable-http-mcp-transport

POR-1480: Streamable HTTP transport for MCP

---

.github/workflows/evals.yml
portia/common.py
tests/unit/test_common.py

- Fix the zendesk eval issue where sometimes models gets passed as pydantic base models and we need to transform it to jsons in constructing the args.
- Update the daily runs for evals to reference the new threshold folders.
**NOTE**: This PR should be merged after the platform one https://github.com/portiaAI/platform/pull/503 

[POR-1442] Fix parsing params for tools and update daily runs thresholds

---

portia/execution_hooks.py
tests/unit/test_execution_hooks.py

At runtime, clarification objects loose their type so you cannot do `isinstance` or use type-specific methods.
This can probably be fixed fairly easily but getting a fix in first.

Fix tool clarification exec hook handling

---

portia/cli.py
portia/templates/tool_description.xml.jinja
portia/tool.py

⚠️ This impacts the main planner prompt slightly since I've changed the jinja template: I've added `| safe` on descriptions to remove the HTML escapes for e.g. apostrophes (no more `&amp;#39;&amp;#39;`). Also improved the args list by removing extra newlines and adding dash in front.
Fix bug in serialising Tool by replacing model-dump with pretty format
Sample from `portia-cli list-tools`:
```
-----------------------------------------------------------------------------------------------------------
| Portia Google Calendar Get Events By Properties Tool (portia:google:gcalendar:get_events_by_properties) |
-----------------------------------------------------------------------------------------------------------
---
Gets Google Calendar events by properties, returning the matching event …
```

Fix CLI tool list serialisation error and improve descriptions

---

.github/workflows/ruff.yml
portia/__init__.py
portia/tool_decorator.py
tests/unit/test_tool_decorator.py
uv.lock

add tool decorator for creating tools from functions
now you can create tool via
```python
@tool
def multiply_numbers(a: float, b: float) -> float:
"""Multiply two numbers together."""
return a * b
@tool
def calculate_area(
length: Annotated[float, Field(description="The length of the rectangle")],
width: Annotated[float, Field(description="The width of the rectangle", gt=0)]
) -> float:
"""Calculate the area of a rectangle."""
return length * width
```
Ticket Link: https://github.com/portiaAI/portia-sdk-python/issues/466
No screenshots taken but here is an example run and its output - https://gist.github.com/jingkaihe/99cf7db3f5fa8e5e40f9e1bead30dab2

Add feature tool decorator

---

portia/tool_registry.py

Deep copy was causing an issue due to lack of ability to deepcopy threadlocks
- [ X] Bug fix 

Fix tool registry for remote tools

---

portia/tool_registry.py
tests/unit/test_tool_registry.py
uv.lock

Using the MCP SDK to connect to a bad SSE url leads to a very long / permanent hang, which the various timeout settings to no help with. 
This PR using `asyncio.wait_for` to work around this.
Also other small fixes:
- Handle tool description validation problems by filtering them out with a warning (not perfect, but better than failing entire server)
- Bump MCP version - noticed some issues with twilio mcp on current version
Related PR https://github.com/portiaAI/platform/pull/647

Improve timeout handling to handle SSE issues

---

portia/config.py
portia/portia.py
tests/unit/test_config.py
tests/unit/test_portia.py

- Fixing the default config to be ONE_SHOT agent to be the default from config.
- Update `GEMINI_2_5_PRO` model and remove `preview`.

Fixing the default config to be ONE_SHOT agent

---

portia/config.py
portia/model.py
tests/unit/test_model.py
uv.lock

- Fixing the warnings of thinking models that appears with anthropic.
-  Need to upgrade the uv.lock for langchain-anthropic here and evals in platform (different PR for platform coming).
- Fixing another bug discovered when using thinking as default execution model. It gave an error that couldn't parse the content of the message (because it's al list output from AIMessage) - Added a unit test for it.

[POR-1685] Added a fix for anthropic warnings

---

portia/logger.py
portia/portia.py
portia/tool_decorator.py
tests/unit/test_logging.py
tests/unit/test_tool_decorator.py

Without stack traces its hard to find the root cause of issues. It also makes every problem look like it comes from Portia, when the errors might be upstream.
Also added a validation on the tool decorator as I hit an issue that was non obvious.
Sample logs:
```
2025-07-11 16:14:12.840 | ERROR | portia.storage:log_tool_call:352 - Tool returned error | {'output': 'test'}
2025-07-11 16:14:12.921 | ERROR | portia.portia:_execute_plan_run:1023 - Error executing step 0: Tool llm_tool failed after retries: Error: ToolSoftError(Exception('test'))
Please fix your mistakes.
Traceback (most recent call last):
File "/Users/samstephens/dev/portia-sdk-python/portia/portia.py", line 1021, in _execute_plan_run
last_executed_step_output = agent.execute_sync()
File …
```

Log the stack trace when exiting plan run with error

---

portia/execution_agents/execution_utils.py
tests/unit/execution_agents/test_execution_utils.py

Better error message + ToolSoftError means there is a chance that we get a success on retry

Bugfix: raise ToolSoftError when LLM introduces templated variables not in step inputs

---

portia/open_source_tools/browser_tool.py
pyproject.toml
tests/unit/open_source_tools/test_browser_tool.py
uv.lock

Browseruse now uses Playwright + Chromium in "local mode" by default. This is actually kind of nice and isolated, but it does have some issues:
* The browser closes at the end of the agent run, by default. This means clarifications for auth can't be completed because there is nowhere to enter the info
* To solve the above, you can add "keep-alive", but to ensure playwright connects to the same browser process on resume, you have to track the browser PID, and you have to implement killing the Chromium instance after completion.
* Browseruse appears to not clean up the playwright process correctly when closing the browser.
It seems like there is a bug that means playwright + Chromium is the only option that works at the moment, i.e. you can't connect to Chrome - at least I'm getting the …

Browseruse fixes for local infra option

---

portia/open_source_tools/search_tool.py

https://docs.tavily.com/documentation/api-reference/endpoint/search#authorization-authorization
Tavily's search API used to send the api key in the request payload but according to api docs it expects in the header.

Move api_key to authorization header for search tool

---

portia/portia.py
tests/unit/test_portia.py

Allows multiple input types for plan identification. Users can now use Plan objects, PlanUUID objects, raw UUID objects, and plan ID strings interchangeably.
```
portia.run_plan(plan)
portia.run_plan(plan)                    # Plan object
portia.run_plan(plan.id)                 # PlanUUID
portia.run_plan(plan.id.uuid)            # Raw UUID
plan_id_1 = PlanUUID.from_string("plan-f66b141b-5603-4bd9-b827-0c7a41bf5d5c")
plan_id_2 = "plan-f66b141b-5603-4bd9-b827-0c7a41bf5d5c"
portia.plan(
query="Get the weather in Paris",
example_plans=[plan_id_1, plan_id_2]  # Mixed types supported
)
```
Ticket Link: https://github.com/portiaAI/portia-sdk-python/issues/574
- Unit Tests
- Tested by trying portia plan in example.py - Run this https://pastebin.com/7fEN38j9

 Provide example plans by ID

---

portia/planning_agents/default_planning_agent.py

There have been a number of recent eval drops on anthropic particularly for is_plan_generated. Full analysis is [here](https://docs.google.com/document/d/13hT0M4ta-Q3JoMmYNIlmsxa-xqvi3B270b_sbcw0Z0w/edit?tab=t.0). But to summarise, this is mostly one eval that is failing because it _wants_ an error to be produced but instead the planner is hallucinating a second plan input that doesn't exist.
Over 200 runs on that particular eval, the is_plan_generated metric increased from 0.4 to 0.8 and running across the complete eval set showed no drop on other metrics so I think worth getting this in.

Adjust planning prompt

---

portia/tool.py
portia/tool_registry.py
tests/unit/test_tool.py
tests/unit/test_tool_registry.py

- Fixed serialisation of pydantic objects to JSON when they found nested within Python objects (e.g. list of pydantic objects)
- Support JSON schema `additionalProperties` on objects by allowing extra fields on the pydantic object, and validating the types if provided. 
Ticket Link: [POR-1767](https://linear.app/portialabs/issue/POR-1767/fix-notion-create-pages-tool-schema-is-incompatible-with-sdk)

Support additionalProperties and improve serialisation of pydantic objects

---

portia/logger.py
portia/portia.py
tests/unit/test_logging.py
uv.lock

Previously, the stack traces in the Stripe demo were causing an error for the logger because they had unescaped quotation marks. I've fixed that by sanitising the stack trace too. However, I also think the stack trace wasn't really needed for tool errors, so I've also combined it with the .error() message below.

Fix logging exceptions within Stripe demo

---

portia/mcp_session.py
portia/tool.py
portia/tool_registry.py
tests/unit/test_tool.py
uv.lock

Tested this many times locally - it stops the tool call without hanging, which was an issue with only using the sse_read_timeout setting

Add an optional timeout for tool calls

---

CONTRIBUTING.md

During the code setup for development, the command to install dependencies `uv install --all-extras` is not correct. Modified the command with the one that is working.
The following error occurred when I ran `uv install --all-extras`
```
error: unrecognized subcommand 'install'
tip: a similar subcommand exists: 'uv pip install'
Usage: uv [OPTIONS] <COMMAND>
```
The following error occurred when I ran `uv pip install --all-extras`
```
error: the following required arguments were not provided:
<PACKAGE|--requirements <REQUIREMENTS>|--editable <EDITABLE>|--group <GROUP>>
Usage: uv pip install --all-extras <PACKAGE|--requirements <REQUIREMENTS>|--editable <EDITABLE>|--group <GROUP>>
For more information, try '--help'.
```
Please let me know if this is okay.

Update dependency installing command in CONTRIBUTION.md

---

README.md
portia/config.py
portia/execution_agents/default_execution_agent.py
portia/execution_agents/one_shot_agent.py
portia/execution_agents/utils/final_output_summarizer.py
portia/execution_agents/utils/step_summarizer.py
portia/introspection_agents/default_introspection_agent.py
portia/logger.py
portia/model.py
portia/open_source_tools/llm_tool.py
portia/planning_agents/default_planning_agent.py
tests/unit/test_logging.py

Introduce a new TRACE logging level and emit trace logs for every LLM call across the SDK. TRACE includes all DEBUG logs plus a one-line “LLM call” entry showing the model and the high-level purpose (planning, introspection, summarization, argument parsing/verification, tool-calling). Updated README to document how to enable TRACE.
Ticket Link: https://github.com/portiaAI/portia-sdk-python/issues/607
Added TRACE logging level and per-LLM-call trace lines across agents and LLMTool; documented usage in README.

feat(trace-logging): add TRACE level and LLM call traces (#607)

---

portia/open_source_tools/llm_tool.py
tests/unit/open_source_tools/test_llm_tool.py

Sometimes there is an issue where a model (e.g gemini-1.5) is generating a LLMTool call with Dict instead of str or list for `task_data`. So adding dict as another possible input for the LLMTool. This is causing pydantic validation error when executing the tool call. 
[Example trace](https://smith.langchain.com/public/5bbbf3c9-4296-49b8-9a19-859e6a930e36/r)
Ticket Link: https://github.com/portiaAI/portia-sdk-python/issues/717

[Issue#717] Fix LLMTool to expect dict as well

---

portia/builder/reference.py
portia/portia.py
tests/unit/builder/test_reference.py
tests/unit/builder/test_step_v2.py

Previously, if steps were skipped due to an if statement, they wouldn't give out outputs and so this meant that we didn't pick the correct step output value. This PR fixes it by tracking name + step index with the output and using that when we do the lookup.

Ensure step outputs can be referenced correctly

---

.github/workflows/ruff.yml
portia/open_source_tools/sql_tool.py
tests/unit/open_source_tools/test_sql_tool.py

Currently, we run `ruff format --check` with pre-commit but not in github actions. This allows code to get in that then doesn't pass the linter in pre-commit. Adding this to GH actions should mean that all code that gets into main passes pre-commit.
Note: We should run pre-commit as part of the Github actions rather than these, so we do the linting in GH the same way that we do linting locally, but for now this should be fine.

Update linting github actions

---

portia/builder/reference.py
portia/builder/step_v2.py
pyproject.toml
tests/integration/test_plan_v2.py
tests/unit/builder/test_reference.py
tests/unit/builder/test_step_v2.py
uv.lock

Allows specifying StepOutput("step_name", path="field_a.field_b") or similar for Input to access sub-paths of the output / input.

Allow reference sub-path in an Input / Output

---

portia/tool.py
tests/unit/test_tool.py

Improve ugly MCP tool response formatting by unpacking the response from the MCP SDK `CallToolResponse` object if it is an object with a single TextContent within it (the most common case).

Unpack MCP tool response if it is a simple TextContent block

---

portia/__init__.py
portia/cost_estimator.py
tests/integration/test_cost_estimator_integration.py
tests/unit/test_cost_estimator.py

This PR implements a comprehensive cost estimator tool that allows users to estimate the LLM costs of running Portia plans before execution. The feature provides detailed cost breakdowns and explanations to help users make informed decisions about their agentic workflows.
Ticket Link: https://github.com/portiaAI/portia-sdk-python/issues/646
Added
CostEstimator class for estimating LLM costs of Portia plans
PlanCostEstimate and StepCostEstimate data models for structured cost information
Comprehensive model pricing database covering 18 LLM providers
Extensive unit and integration test coverage
Cost estimation for execution agents, introspection agents, and LLM tools

feat: Add LLM cost estimation
